### ISSUE TITLE
Replace String usage for char buffer to avoid memory crashes

### ISSUE THREAD

**Issue by DonBrus** [Tech1k/helloesp#2]
In reference to commit [917aec6](https://github.com/Tech1k/helloesp/commit/917aec61bc98e43e734f440d95d49269cf5660a3), which forces a periodic restart to avoid memory crashes, I suggest to avoid the usage of __String__ in favor of old fashioned char buffers to convey either static or dynamic information.
Arduino Strings [perform a lot of heap manipulation under the hood](https://github.com/arduino/ArduinoCore-API/blob/master/api/String.cpp), so I'm afraid that repeatedly allocating new ones for serving requests will quickly lead to fragmentation issues which in turn will slow down the execution until it'll eventually grind to a halt.

My suggestions are:
- The webpage does not need to be dynamically changed; turn it into a const char *
   - Same goes for robots.txt
- When displaying the memory usage, use e.g. **snprintf** onto a reasonably sized char buffer. That way you don't have to create a String thrice.
-  Same goes for visitors: just read a line and send it over without turning it into a string (if possible)
   - Also you may want to reduce the writes to SPIFFS when having to update the visitor count by e.g. buffering it into RAM and only updating it every x minutes or n visitors... otherwise you'll destroy the NVM memory pretty quickly.

Let me know what you think.

**Comment by Tech1k** [comment]
Sorry for the late reply, the ESP that hosted the website has burned out, but if I ever consider restarting the website, I'll take your suggestions into consideration!
